### ISSUE TITLE
Fails to Install on SmartOS 15.1.0

### ISSUE THREAD

**Issue by colstrom** [JScott/robot_sweatshop#14]
```
[root@sweatshop ~]# gem install robot_sweatshop
Fetching: contracts-0.9.gem (100%)
Successfully installed contracts-0.9
Fetching: moneta-0.8.0.gem (100%)
Successfully installed moneta-0.8.0
Fetching: configatron-4.5.0.gem (100%)
Successfully installed configatron-4.5.0
Fetching: colorize-0.7.7.gem (100%)
Successfully installed colorize-0.7.7
Fetching: sigar-0.7.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing robot_sweatshop:
        ERROR: Failed to build gem native extension.

    /opt/local/bin/ruby22 -r ./siteconf20150522-72569-1au3ryu.rb extconf.rb
Ruby platform=x86_64-solaris2.11
checking for main() in -lnsl... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/local/bin/$(RUBY_BASE_NAME)22
        --with-nsllib
        --without-nsllib
/opt/local/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from /opt/local/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
        from extconf.rb:54:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /opt/local/lib/ruby/gems/2.2.0/gems/sigar-0.7.3 for inspection.
Results logged to /opt/local/lib/ruby/gems/2.2.0/extensions/x86_64-solaris-2.11/2.2.0/sigar-0.7.3/gem_make.out
```

**Comment by colstrom** [comment]
Looks like this relates to [SIGAR Issue #27](https://github.com/hyperic/sigar/issues/27).
